import { APP_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'apps',
        path: '',
        title: 'APPS',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'apps.jobcard',
                path: '',
                title: 'Jobcard',
                translateKey: 'nav.appsJobcard.jobcard',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsJobcard.jobcardNew',
                        path: `${APP_PREFIX_PATH}/jobcards/jobcard-new`,
                        title: 'Create Jobcard',
                        translateKey: 'nav.appsJobcard.jobcardNew',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsJobcard.jobcardList',
                        path: `${APP_PREFIX_PATH}/jobcards/jobcard-list`,
                        title: 'Jobcard List',
                        translateKey: 'nav.appsJobcard.jobcardList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },{
                        key: 'appsJobcard.pendingList',
                        path: `${APP_PREFIX_PATH}/jobcards/pending-list`,
                        title: 'Pending List',
                        translateKey: 'nav.appsJobcard.pendingList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsJobcard.returnList',
                        path: `${APP_PREFIX_PATH}/jobcards/return-list`,
                        title: 'Return List',
                        translateKey: 'nav.appsJobcard.returnList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsJobcard.completedList',
                        path: `${APP_PREFIX_PATH}/jobcards/completed-list`,
                        title: 'Completed List',
                        translateKey: 'nav.appsJobcard.completedList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsJobcard.billedList',
                        path: `${APP_PREFIX_PATH}/jobcards/billed-list`,
                        title: 'Billed List',
                        translateKey: 'nav.appsJobcard.billedList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsProject.scrumBoard',
                    //     path: `${APP_PREFIX_PATH}/project/scrum-board`,
                    //     title: 'Scrum Board',
                    //     translateKey: 'nav.appsProject.scrumBoard',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsProject.issue',
                    //     path: `${APP_PREFIX_PATH}/project/issue`,
                    //     title: 'Issue',
                    //     translateKey: 'nav.appsProject.issue',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },
            {
                key: 'apps.onsite',
                path: '',
                title: 'OnSite',
                translateKey: 'nav.appsOnsite.onsite',
                icon: 'common',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsOnsite.onsiteNew',
                        path: `${APP_PREFIX_PATH}/onsite/form`,
                        title: 'Create onsite',
                        translateKey: 'nav.appsOnsite.onsiteNew',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOnsite.onsiteList',
                        path: `${APP_PREFIX_PATH}/onsite`,
                        title: 'Onsite List',
                        translateKey: 'nav.onsiteList.onsiteList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },{
                        key: 'appsOnsite.pendingList',
                        path: `${APP_PREFIX_PATH}/onsite-pending`,
                        title: 'Pending List',
                        translateKey: 'nav.appsOnsite.pendingList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOnsite.closedList',
                        path: `${APP_PREFIX_PATH}/onsite-closed`,
                        title: 'Closed List',
                        translateKey: 'nav.appsOnsite.closedList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOnsite.sentList',
                        path: `${APP_PREFIX_PATH}/onsite-sent`,
                        title: 'Sent to Workshop List',
                        translateKey: 'nav.appsOnsite.sentList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    
                ],
            },
            {
                key: 'apps.worker',
                path: '',
                title: 'worker',
                translateKey: 'nav.appsWorker.worker',
                icon: 'crm',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    
                    {
                        key: 'appsWorker.workerList',
                        path: `${APP_PREFIX_PATH}/worker`,
                        title: 'Worker List',
                        translateKey: 'nav.appsWorker.workerList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    
                ],
            },
        ],
    },
]

export default appsNavigationConfig
