export const APP_NAME = 'Igniteway'
export const PERSIST_STORE_NAME = 'admin'
export const REDIRECT_URL_KEY = 'redirectUrl'
// export const BASE_URL = 'http://localhost:9037/api'
export const BASE_URL = 'https://hitechengineeringcompany.in/api'
